title: Austin's Website
author: Austin Blizard 
email: apbliz2004@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Austin, I'm 17 & I work at Walgreens!

# social links
instagram_username: austinblizard # DO NOT include the @ character, or else the build will fail!
github_username:  austinblizard # DO NOT include the @ character, or else the build will fail!
snapchat_username:  austinbliz04 
show_excerpts: true # set to false to remove excerpts on the homepage
