title: Austin's Website
author: Austin Blizard 
email: apbliz2004@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Austin, I'm 16 & I currently work at Walgreens!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  austinblizard # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

---
title: "My Blog"
date: 2021-01-23
---
